export const skipperModels = new Map([
    ['modelMarin', {
        sigmaB: true,
        sigmaF: true,
        bsigma: true,
        sigma1: true,
        mysigma: false,
        tauB: false,
        tauF: false,
        btau: false,
        tau1: false,
        mytau: false,
    }],
    ['modelCrossland', {
        sigmaB: true,
        sigmaF: false,
        bsigma: false,
        sigma1: false,
        mysigma: false,
        tauB: false,
        tauF: true,
        btau: true,
        tau1: true,
        mytau: false,
    }],
    ['modelCrossland+', {
        sigmaB: true,
        sigmaF: false,
        bsigma: false,
        sigma1: false,
        mysigma: false,
        tauB: true,
        tauF: true,
        btau: true,
        tau1: true,
        mytau: false,
    }],
    ['modelSains', {
        sigmaB: true,
        sigmaF: false,
        bsigma: false,
        sigma1: false,
        mysigma: false,
        tauB: false,
        tauF: true,
        btau: true,
        tau1: true,
        mytau: false,
    }],
    ['modelYancin', {
        sigmaB: true,
        sigmaF: true,
        bsigma: true,
        sigma1: true,
        mysigma: true,
        tauB: true,
        tauF: true,
        btau: true,
        tau1: true,
        mytau: true,
    }]
]);